### ISSUE TITLE
/forecast?insee=95026 retourne un tableau vide

### ISSUE THREAD

**Issue by DavidBruant** [l-vincent-l/indice_pollution#5]
URL : https://app-6ccdcc10-da92-47b1-add6-59d8d3914d79.cleverapps.io/forecast?insee=95026

Je m'attendrai plutôt à un 404 qu'à un 200 avec tableau vide

**Comment by l-vincent-l** [comment]
je pense que l'API a du renvoyer un truc vide, et vu que y a du cache ça retourne toujours un truc vide.

J'ai mis du retry en cas de retour vide

**Comment by DavidBruant** [comment]
Trop bien, merci ^^
